{
 "title": "DOTNET - Laboratório de Observabilidade",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status da API",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"dotnet-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Previsões Geradas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_forecast_generated_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count{http_route=\"/weatherforecast\"}[1m])",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Memória GC Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erros 5xx por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count{http_route=\"/weatherforecast\", http_response_status_code=\"500\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência da API (Percentis)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, irate(http_server_request_duration_seconds_bucket{http_route=\"/weatherforecast\"}[1m]))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, irate(http_server_request_duration_seconds_bucket{http_route=\"/weatherforecast\"}[1m]))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, irate(http_server_request_duration_seconds_bucket{http_route=\"/weatherforecast\"}[1m]))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}