{
 "title": "JAVA - Laboratório de Observabilidade",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status da API",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"java-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Produtos Criados",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "products_created_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pedidos Ativos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orders_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requisições por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"java-api\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Memória JVM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"java-api\"}",
     "legendFormat": "{{area}} - {{id}}"
    }
   ]
  },
  {
   "title": "Erros 5xx por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"java-api\", status=~\"5..\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latência da API (Percentis)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_server_requests_seconds_bucket{job=\"java-api\"}[1m]))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(http_server_requests_seconds_bucket{job=\"java-api\"}[1m]))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_server_requests_seconds_bucket{job=\"java-api\"}[1m]))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}