{
 "title": "NGINX - Laboratório de Observabilidade",
 "time": { "from": "2026-02-07T08:12:39.280Z", "to": "2026-02-07T14:12:39.280Z" },
 "panels": [
  {
   "title": "Status do Nginx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Conexões Ativas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total de Requisições",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requisições por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}