{
 "title": "PYTHON - Laboratório de Observabilidade",
 "tags": [
  "python-api",
  "python",
  "api",
  "fastapi"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status da API",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"python-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Requisições POST /items",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{job=\"python-api\", http_method=\"POST\", http_target=\"/items\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Requisições POST /users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{job=\"python-api\", http_method=\"POST\", http_target=\"/users\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_count{job=\"python-api\"}[1m])",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Uso de Memória Python",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"python-api\"}",
     "legendFormat": "Memória Residente"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"python-api\"}",
     "legendFormat": "Memória Virtual"
    }
   ]
  },
  {
   "title": "Erros 5xx por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_count{job=\"python-api\", http_status_code=~\"5..\"}[1m])",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Latência da API (Percentis)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_server_duration_milliseconds_bucket{job=\"python-api\"}[1m])) / 1000",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(http_server_duration_milliseconds_bucket{job=\"python-api\"}[1m])) / 1000",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_server_duration_milliseconds_bucket{job=\"python-api\"}[1m])) / 1000",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}